steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/visitor-clustering-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/visitor-clustering-app']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'visitor-clustering-app', '--image', 'gcr.io/$PROJECT_ID/visitor-clustering-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
- gcr.io/$PROJECT_ID/visitor-clustering-app
